/**
 * Color theme presets (light + dark variants).
 * Tokens map 1:1 to shadcn CSS variables in globals.css.
 * Values are opaque hex for native color inputs and VTable canvas.
 */

export type ThemeTokens = {
  background: string;
  foreground: string;
  card: string;
  cardForeground: string;
  popover: string;
  popoverForeground: string;
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  muted: string;
  mutedForeground: string;
  accent: string;
  accentForeground: string;
  destructive: string;
  destructiveForeground: string;
  border: string;
  input: string;
  ring: string;
  selection: string;
  sidebarBackground: string;
  sidebarForeground: string;
  sidebarPrimary: string;
  sidebarPrimaryForeground: string;
  sidebarAccent: string;
  sidebarAccentForeground: string;
  sidebarBorder: string;
  sidebarRing: string;
  chart1: string;
  chart2: string;
  chart3: string;
  chart4: string;
  chart5: string;
};

export type ColorThemeConfig = {
  preset: string;
  overrides?: {
    light?: Partial<ThemeTokens>;
    dark?: Partial<ThemeTokens>;
  };
};

export type ColorThemePreset = {
  id: string;
  name: string;
  light: ThemeTokens;
  dark: ThemeTokens;
};

export const THEME_TOKEN_KEYS = [
  'background',
  'foreground',
  'card',
  'cardForeground',
  'popover',
  'popoverForeground',
  'primary',
  'primaryForeground',
  'secondary',
  'secondaryForeground',
  'muted',
  'mutedForeground',
  'accent',
  'accentForeground',
  'destructive',
  'destructiveForeground',
  'border',
  'input',
  'ring',
  'selection',
  'sidebarBackground',
  'sidebarForeground',
  'sidebarPrimary',
  'sidebarPrimaryForeground',
  'sidebarAccent',
  'sidebarAccentForeground',
  'sidebarBorder',
  'sidebarRing',
  'chart1',
  'chart2',
  'chart3',
  'chart4',
  'chart5',
] as const satisfies readonly (keyof ThemeTokens)[];

/** Map ThemeTokens key → CSS custom property name (without leading --). */
export function tokenToCssVarName(key: keyof ThemeTokens): string {
  return key
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([a-zA-Z])(\d)/g, '$1-$2')
    .toLowerCase();
}

export function hasColorOverrides(
  overrides?: ColorThemeConfig['overrides'] | null,
  mode?: 'light' | 'dark',
): boolean {
  if (!overrides) return false;
  if (mode) {
    const m = overrides[mode];
    return !!m && Object.keys(m).length > 0;
  }
  return (
    (!!overrides.light && Object.keys(overrides.light).length > 0) ||
    (!!overrides.dark && Object.keys(overrides.dark).length > 0)
  );
}

/** Current globals.css values as hex (matches tables/theme.ts palette). */
const DEFAULT_LIGHT: ThemeTokens = {
  background: '#ffffff',
  foreground: '#0d0f12',
  card: '#ffffff',
  cardForeground: '#0d0f12',
  popover: '#ffffff',
  popoverForeground: '#0d0f12',
  primary: '#2f68da',
  primaryForeground: '#ffffff',
  secondary: '#f4f5f7',
  secondaryForeground: '#16181d',
  muted: '#f4f5f7',
  mutedForeground: '#6c727e',
  accent: '#fff7d6',
  accentForeground: '#8a4d0f',
  destructive: '#ef4444',
  destructiveForeground: '#ffffff',
  border: '#e2e5ea',
  input: '#e2e5ea',
  ring: '#2f68da',
  selection: '#fff0c2',
  sidebarBackground: '#f7f8f9',
  sidebarForeground: '#454a54',
  sidebarPrimary: '#2f68da',
  sidebarPrimaryForeground: '#ffffff',
  sidebarAccent: '#fff7d6',
  sidebarAccentForeground: '#8a4d0f',
  sidebarBorder: '#e2e5ea',
  sidebarRing: '#2f68da',
  chart1: '#e76e50',
  chart2: '#2a9d8f',
  chart3: '#274653',
  chart4: '#e9c46a',
  chart5: '#f4a261',
};

const DEFAULT_DARK: ThemeTokens = {
  background: '#171b21',
  foreground: '#f2f2f2',
  card: '#24282f',
  cardForeground: '#f2f2f2',
  popover: '#282d36',
  popoverForeground: '#f2f2f2',
  primary: '#477eeb',
  primaryForeground: '#ffffff',
  secondary: '#282d36',
  secondaryForeground: '#f2f2f2',
  muted: '#282d36',
  mutedForeground: '#8f96a3',
  accent: '#3d3520',
  accentForeground: '#f5e5a3',
  destructive: '#811d1d',
  destructiveForeground: '#ffffff',
  border: '#3b414a',
  input: '#3b414a',
  ring: '#477eeb',
  selection: '#4a3f1f',
  sidebarBackground: '#121418',
  sidebarForeground: '#d3d6dc',
  sidebarPrimary: '#477eeb',
  sidebarPrimaryForeground: '#ffffff',
  sidebarAccent: '#3d3520',
  sidebarAccentForeground: '#f5e5a3',
  sidebarBorder: '#2a2f37',
  sidebarRing: '#477eeb',
  chart1: '#2662d9',
  chart2: '#2eb85c',
  chart3: '#e88c30',
  chart4: '#8357db',
  chart5: '#e236a9',
};

export const colorThemePresets: ColorThemePreset[] = [
  {
    id: 'default',
    name: 'Default',
    light: DEFAULT_LIGHT,
    dark: DEFAULT_DARK,
  },
  {
    id: 'github',
    name: 'GitHub',
    light: {
      background: '#ffffff',
      foreground: '#1f2328',
      card: '#ffffff',
      cardForeground: '#1f2328',
      popover: '#ffffff',
      popoverForeground: '#1f2328',
      primary: '#0969da',
      primaryForeground: '#ffffff',
      secondary: '#f6f8fa',
      secondaryForeground: '#1f2328',
      muted: '#f6f8fa',
      mutedForeground: '#59636e',
      accent: '#ddf4ff',
      accentForeground: '#0969da',
      destructive: '#d1242f',
      destructiveForeground: '#ffffff',
      border: '#d1d9e0',
      input: '#d1d9e0',
      ring: '#0969da',
      selection: '#b6e3ff',
      sidebarBackground: '#f6f8fa',
      sidebarForeground: '#1f2328',
      sidebarPrimary: '#0969da',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#ddf4ff',
      sidebarAccentForeground: '#0969da',
      sidebarBorder: '#d1d9e0',
      sidebarRing: '#0969da',
      chart1: '#0969da',
      chart2: '#1a7f37',
      chart3: '#9a6700',
      chart4: '#cf222e',
      chart5: '#8250df',
    },
    dark: {
      background: '#212830',
      foreground: '#d1d7e0',
      card: '#262c36',
      cardForeground: '#d1d7e0',
      popover: '#2d333b',
      popoverForeground: '#d1d7e0',
      primary: '#316dca',
      primaryForeground: '#ffffff',
      secondary: '#2d333b',
      secondaryForeground: '#d1d7e0',
      muted: '#2d333b',
      mutedForeground: '#9198a1',
      accent: '#1e3a5f',
      accentForeground: '#6cb6ff',
      destructive: '#e5534b',
      destructiveForeground: '#ffffff',
      border: '#3d444d',
      input: '#3d444d',
      ring: '#316dca',
      selection: '#2f4c6e',
      sidebarBackground: '#1c2128',
      sidebarForeground: '#d1d7e0',
      sidebarPrimary: '#316dca',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#1e3a5f',
      sidebarAccentForeground: '#6cb6ff',
      sidebarBorder: '#373e47',
      sidebarRing: '#316dca',
      chart1: '#539bf5',
      chart2: '#57ab5a',
      chart3: '#c69026',
      chart4: '#e5534b',
      chart5: '#b083f0',
    },
  },
  {
    id: 'catppuccin',
    name: 'Catppuccin',
    light: {
      background: '#eff1f5',
      foreground: '#4c4f69',
      card: '#ffffff',
      cardForeground: '#4c4f69',
      popover: '#ffffff',
      popoverForeground: '#4c4f69',
      primary: '#1e66f5',
      primaryForeground: '#ffffff',
      secondary: '#e6e9ef',
      secondaryForeground: '#4c4f69',
      muted: '#e6e9ef',
      mutedForeground: '#6c6f85',
      accent: '#dbe6fb',
      accentForeground: '#1e66f5',
      destructive: '#d20f39',
      destructiveForeground: '#ffffff',
      border: '#ccd0da',
      input: '#ccd0da',
      ring: '#1e66f5',
      selection: '#c3d5f8',
      sidebarBackground: '#e6e9ef',
      sidebarForeground: '#4c4f69',
      sidebarPrimary: '#1e66f5',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#dbe6fb',
      sidebarAccentForeground: '#1e66f5',
      sidebarBorder: '#bcc0cc',
      sidebarRing: '#1e66f5',
      chart1: '#1e66f5',
      chart2: '#40a02b',
      chart3: '#fe640b',
      chart4: '#8839ef',
      chart5: '#179299',
    },
    dark: {
      background: '#1e1e2e',
      foreground: '#cdd6f4',
      card: '#282840',
      cardForeground: '#cdd6f4',
      popover: '#282840',
      popoverForeground: '#cdd6f4',
      primary: '#89b4fa',
      primaryForeground: '#1e1e2e',
      secondary: '#313244',
      secondaryForeground: '#cdd6f4',
      muted: '#313244',
      mutedForeground: '#a6adc8',
      accent: '#30364e',
      accentForeground: '#89b4fa',
      destructive: '#f38ba8',
      destructiveForeground: '#1e1e2e',
      border: '#45475a',
      input: '#45475a',
      ring: '#89b4fa',
      selection: '#3d4059',
      sidebarBackground: '#181825',
      sidebarForeground: '#cdd6f4',
      sidebarPrimary: '#89b4fa',
      sidebarPrimaryForeground: '#1e1e2e',
      sidebarAccent: '#30364e',
      sidebarAccentForeground: '#89b4fa',
      sidebarBorder: '#313244',
      sidebarRing: '#89b4fa',
      chart1: '#89b4fa',
      chart2: '#a6e3a1',
      chart3: '#fab387',
      chart4: '#cba6f7',
      chart5: '#94e2d5',
    },
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    light: {
      background: '#e1e2e7',
      foreground: '#3760bf',
      card: '#eceef3',
      cardForeground: '#3760bf',
      popover: '#f5f6f9',
      popoverForeground: '#3760bf',
      primary: '#2e7de9',
      primaryForeground: '#ffffff',
      secondary: '#d0d5e3',
      secondaryForeground: '#3760bf',
      muted: '#d0d5e3',
      mutedForeground: '#848cb5',
      accent: '#c8d2e8',
      accentForeground: '#2e7de9',
      destructive: '#f52a65',
      destructiveForeground: '#ffffff',
      border: '#c4c8da',
      input: '#c4c8da',
      ring: '#2e7de9',
      selection: '#bcc9e6',
      sidebarBackground: '#d0d5e3',
      sidebarForeground: '#3760bf',
      sidebarPrimary: '#2e7de9',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#c8d2e8',
      sidebarAccentForeground: '#2e7de9',
      sidebarBorder: '#b6bbd0',
      sidebarRing: '#2e7de9',
      chart1: '#2e7de9',
      chart2: '#587539',
      chart3: '#b15c00',
      chart4: '#9854f1',
      chart5: '#007197',
    },
    dark: {
      background: '#24283b',
      foreground: '#c0caf5',
      card: '#1f2335',
      cardForeground: '#c0caf5',
      popover: '#1f2335',
      popoverForeground: '#c0caf5',
      primary: '#7aa2f7',
      primaryForeground: '#1a1b26',
      secondary: '#292e42',
      secondaryForeground: '#c0caf5',
      muted: '#292e42',
      mutedForeground: '#565f89',
      accent: '#283457',
      accentForeground: '#7aa2f7',
      destructive: '#f7768e',
      destructiveForeground: '#1a1b26',
      border: '#3b4261',
      input: '#3b4261',
      ring: '#7aa2f7',
      selection: '#364a82',
      sidebarBackground: '#1f2335',
      sidebarForeground: '#c0caf5',
      sidebarPrimary: '#7aa2f7',
      sidebarPrimaryForeground: '#1a1b26',
      sidebarAccent: '#283457',
      sidebarAccentForeground: '#7dcfff',
      sidebarBorder: '#2f3549',
      sidebarRing: '#7aa2f7',
      chart1: '#7aa2f7',
      chart2: '#9ece6a',
      chart3: '#ff9e64',
      chart4: '#bb9af7',
      chart5: '#7dcfff',
    },
  },
  {
    id: 'gruvbox',
    name: 'Gruvbox',
    light: {
      background: '#fbf1c7',
      foreground: '#3c3836',
      card: '#f9f5d7',
      cardForeground: '#3c3836',
      popover: '#f9f5d7',
      popoverForeground: '#3c3836',
      primary: '#458588',
      primaryForeground: '#fbf1c7',
      secondary: '#ebdbb2',
      secondaryForeground: '#3c3836',
      muted: '#ebdbb2',
      mutedForeground: '#7c6f64',
      accent: '#ebdbb2',
      accentForeground: '#3c3836',
      destructive: '#cc241d',
      destructiveForeground: '#fbf1c7',
      border: '#d5c4a1',
      input: '#d5c4a1',
      ring: '#458588',
      selection: '#e0cfa9',
      sidebarBackground: '#f2e5bc',
      sidebarForeground: '#3c3836',
      sidebarPrimary: '#458588',
      sidebarPrimaryForeground: '#fbf1c7',
      sidebarAccent: '#ebdbb2',
      sidebarAccentForeground: '#3c3836',
      sidebarBorder: '#d5c4a1',
      sidebarRing: '#458588',
      chart1: '#458588',
      chart2: '#98971a',
      chart3: '#d65d0e',
      chart4: '#b16286',
      chart5: '#689d6a',
    },
    dark: {
      background: '#282828',
      foreground: '#ebdbb2',
      card: '#32302f',
      cardForeground: '#ebdbb2',
      popover: '#3c3836',
      popoverForeground: '#ebdbb2',
      primary: '#83a598',
      primaryForeground: '#282828',
      secondary: '#3c3836',
      secondaryForeground: '#ebdbb2',
      muted: '#3c3836',
      mutedForeground: '#a89984',
      accent: '#504945',
      accentForeground: '#ebdbb2',
      destructive: '#fb4934',
      destructiveForeground: '#282828',
      border: '#504945',
      input: '#504945',
      ring: '#83a598',
      selection: '#5a524c',
      sidebarBackground: '#1d2021',
      sidebarForeground: '#ebdbb2',
      sidebarPrimary: '#83a598',
      sidebarPrimaryForeground: '#282828',
      sidebarAccent: '#3c3836',
      sidebarAccentForeground: '#fbf1c7',
      sidebarBorder: '#3c3836',
      sidebarRing: '#83a598',
      chart1: '#83a598',
      chart2: '#b8bb26',
      chart3: '#fe8019',
      chart4: '#d3869b',
      chart5: '#8ec07c',
    },
  },
  {
    id: 'solarized',
    name: 'Solarized',
    light: {
      background: '#fdf6e3',
      foreground: '#586e75',
      card: '#f6eed8',
      cardForeground: '#586e75',
      popover: '#fdf6e3',
      popoverForeground: '#586e75',
      primary: '#268bd2',
      primaryForeground: '#fdf6e3',
      secondary: '#eee8d5',
      secondaryForeground: '#586e75',
      muted: '#eee8d5',
      mutedForeground: '#93a1a1',
      accent: '#e9e0c6',
      accentForeground: '#586e75',
      destructive: '#dc322f',
      destructiveForeground: '#fdf6e3',
      border: '#e0d9bd',
      input: '#e0d9bd',
      ring: '#268bd2',
      selection: '#e6dfc3',
      sidebarBackground: '#eee8d5',
      sidebarForeground: '#586e75',
      sidebarPrimary: '#268bd2',
      sidebarPrimaryForeground: '#fdf6e3',
      sidebarAccent: '#e9e0c6',
      sidebarAccentForeground: '#586e75',
      sidebarBorder: '#ddd3b5',
      sidebarRing: '#268bd2',
      chart1: '#268bd2',
      chart2: '#859900',
      chart3: '#cb4b16',
      chart4: '#6c71c4',
      chart5: '#2aa198',
    },
    dark: {
      background: '#002b36',
      foreground: '#93a1a1',
      card: '#073642',
      cardForeground: '#93a1a1',
      popover: '#073642',
      popoverForeground: '#93a1a1',
      primary: '#268bd2',
      primaryForeground: '#002b36',
      secondary: '#073642',
      secondaryForeground: '#93a1a1',
      muted: '#073642',
      mutedForeground: '#586e75',
      accent: '#0e4456',
      accentForeground: '#93a1a1',
      destructive: '#dc322f',
      destructiveForeground: '#fdf6e3',
      border: '#0d4a5c',
      input: '#0d4a5c',
      ring: '#268bd2',
      selection: '#164c5f',
      sidebarBackground: '#00232c',
      sidebarForeground: '#93a1a1',
      sidebarPrimary: '#268bd2',
      sidebarPrimaryForeground: '#002b36',
      sidebarAccent: '#0e4456',
      sidebarAccentForeground: '#93a1a1',
      sidebarBorder: '#0d4a5c',
      sidebarRing: '#268bd2',
      chart1: '#268bd2',
      chart2: '#859900',
      chart3: '#cb4b16',
      chart4: '#6c71c4',
      chart5: '#2aa198',
    },
  },
  {
    id: 'rose-pine',
    name: 'Rosé Pine',
    light: {
      background: '#faf4ed',
      foreground: '#575279',
      card: '#fffaf3',
      cardForeground: '#575279',
      popover: '#fffaf3',
      popoverForeground: '#575279',
      primary: '#286983',
      primaryForeground: '#faf4ed',
      secondary: '#f2e9e1',
      secondaryForeground: '#575279',
      muted: '#f2e9e1',
      mutedForeground: '#797593',
      accent: '#ede3db',
      accentForeground: '#575279',
      destructive: '#b4637a',
      destructiveForeground: '#faf4ed',
      border: '#dfdad9',
      input: '#dfdad9',
      ring: '#286983',
      selection: '#e8ded5',
      sidebarBackground: '#f2e9e1',
      sidebarForeground: '#575279',
      sidebarPrimary: '#286983',
      sidebarPrimaryForeground: '#faf4ed',
      sidebarAccent: '#ede3db',
      sidebarAccentForeground: '#575279',
      sidebarBorder: '#dfdad9',
      sidebarRing: '#286983',
      chart1: '#286983',
      chart2: '#b4637a',
      chart3: '#ea9d34',
      chart4: '#907aa9',
      chart5: '#56949f',
    },
    dark: {
      background: '#191724',
      foreground: '#e0def4',
      card: '#1f1d2e',
      cardForeground: '#e0def4',
      popover: '#26233a',
      popoverForeground: '#e0def4',
      primary: '#9ccfd8',
      primaryForeground: '#191724',
      secondary: '#26233a',
      secondaryForeground: '#e0def4',
      muted: '#26233a',
      mutedForeground: '#908caa',
      accent: '#403d52',
      accentForeground: '#e0def4',
      destructive: '#eb6f92',
      destructiveForeground: '#191724',
      border: '#312e45',
      input: '#312e45',
      ring: '#9ccfd8',
      selection: '#4a4763',
      sidebarBackground: '#14121e',
      sidebarForeground: '#e0def4',
      sidebarPrimary: '#9ccfd8',
      sidebarPrimaryForeground: '#191724',
      sidebarAccent: '#403d52',
      sidebarAccentForeground: '#e0def4',
      sidebarBorder: '#26233a',
      sidebarRing: '#9ccfd8',
      chart1: '#9ccfd8',
      chart2: '#eb6f92',
      chart3: '#f6c177',
      chart4: '#c4a7e7',
      chart5: '#31748f',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    light: {
      background: '#eceff4',
      foreground: '#2e3440',
      card: '#f5f7fa',
      cardForeground: '#2e3440',
      popover: '#f5f7fa',
      popoverForeground: '#2e3440',
      primary: '#5e81ac',
      primaryForeground: '#eceff4',
      secondary: '#e5e9f0',
      secondaryForeground: '#2e3440',
      muted: '#e5e9f0',
      mutedForeground: '#4c566a',
      accent: '#dfe4ec',
      accentForeground: '#2e3440',
      destructive: '#bf616a',
      destructiveForeground: '#eceff4',
      border: '#d8dee9',
      input: '#d8dee9',
      ring: '#5e81ac',
      selection: '#d3dae6',
      sidebarBackground: '#e5e9f0',
      sidebarForeground: '#2e3440',
      sidebarPrimary: '#5e81ac',
      sidebarPrimaryForeground: '#eceff4',
      sidebarAccent: '#dfe4ec',
      sidebarAccentForeground: '#2e3440',
      sidebarBorder: '#d8dee9',
      sidebarRing: '#5e81ac',
      chart1: '#5e81ac',
      chart2: '#a3be8c',
      chart3: '#d08770',
      chart4: '#b48ead',
      chart5: '#8fbcbb',
    },
    dark: {
      background: '#2e3440',
      foreground: '#d8dee9',
      card: '#3b4252',
      cardForeground: '#d8dee9',
      popover: '#3b4252',
      popoverForeground: '#d8dee9',
      primary: '#88c0d0',
      primaryForeground: '#2e3440',
      secondary: '#3b4252',
      secondaryForeground: '#d8dee9',
      muted: '#3b4252',
      mutedForeground: '#a8b3c5',
      accent: '#434c5e',
      accentForeground: '#eceff4',
      destructive: '#bf616a',
      destructiveForeground: '#eceff4',
      border: '#434c5e',
      input: '#434c5e',
      ring: '#88c0d0',
      selection: '#4c566a',
      sidebarBackground: '#272c36',
      sidebarForeground: '#d8dee9',
      sidebarPrimary: '#88c0d0',
      sidebarPrimaryForeground: '#2e3440',
      sidebarAccent: '#434c5e',
      sidebarAccentForeground: '#eceff4',
      sidebarBorder: '#3b4252',
      sidebarRing: '#88c0d0',
      chart1: '#88c0d0',
      chart2: '#a3be8c',
      chart3: '#d08770',
      chart4: '#b48ead',
      chart5: '#8fbcbb',
    },
  },
];

const presetMap = new Map(colorThemePresets.map((p) => [p.id, p]));

export function getColorThemePreset(id: string): ColorThemePreset {
  return presetMap.get(id) ?? colorThemePresets[0]!;
}

export function getEffectiveTokens(
  config: ColorThemeConfig | undefined | null,
  mode: 'light' | 'dark',
): ThemeTokens {
  const presetId = config?.preset ?? 'default';
  const base = getColorThemePreset(presetId)[mode];
  const overrides = config?.overrides?.[mode];
  if (!overrides || Object.keys(overrides).length === 0) return base;
  return { ...base, ...overrides };
}

/**
 * Tokens to inject as inline CSS vars.
 * `null` means clear overrides and use globals.css defaults (default preset, no overrides).
 */
export function tokensForInjection(
  config: ColorThemeConfig | undefined | null,
  mode: 'light' | 'dark',
): ThemeTokens | null {
  const presetId = config?.preset ?? 'default';
  if (presetId === 'default' && !hasColorOverrides(config?.overrides, mode)) {
    return null;
  }
  return getEffectiveTokens(config, mode);
}
